
USE DATABASE {{ RAW }};
CREATE OR REPLACE TABLE RESEARCH.DEPT (
    dept_id INT,
    dept_name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    INSERTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);