use role securityadmin;
create role DEPLOY_ROLE;
grant role sysadmin TO ROLE DEPLOY_ROLE;
grant role deploy_role to role accountadmin;

use role sysadmin;
create warehouse deployment_wh;

use role securityadmin;
CREATE USER SVC_SNOWFLAKE_DEPLOY
  TYPE = SERVICE
  WORKLOAD_IDENTITY = (
    TYPE = AZURE
    ISSUER = 'https://login.microsoftonline.com/740d81d4-e4d6-4689-8d63-22257ff4a74c/v2.0'
    SUBJECT = '78c3a5c0-bc6a-4e54-94e4-16b5ccb38f44'
  )
  DEFAULT_ROLE = DEPLOY_ROLE
  DEFAULT_WAREHOUSE = DEPLOYMENT_WH;


GRANT ROLE DEPLOY_ROLE TO USER SVC_SNOWFLAKE_DEPLOY;
DESC USER SVC_SNOWFLAKE_DEPLOY;

CREATE AUTHENTICATION POLICY config_db.security_sch.DEPLOYMENT_POLICY
  AUTHENTICATION_METHODS = ('WORKLOAD_IDENTITY');


  show authentication policies;
  

  alter user SVC_SNOWFLAKE_DEPLOY set authentication policy config_db.security_sch.DEPLOYMENT_POLICY;

CREATE DATABASE IF NOT EXISTS METADATA;

CREATE SCHEMA IF NOT EXISTS METADATA.SCHEMACHANGE;

GRANT USAGE ON DATABASE METADATA TO ROLE DEPLOY_ROLE;


GRANT USAGE ON SCHEMA METADATA.SCHEMACHANGE TO ROLE DEPLOY_ROLE;

GRANT CREATE TABLE ON SCHEMA METADATA.SCHEMACHANGE TO ROLE DEPLOY_ROLE;